# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "ahci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-3cc39c35-81d3-4f4c-bc0d-176f66523fd7";
      fsType = "ext4";
    };

  boot.initrd.luks.devices."luks-3f1d3add-27cd-4b76-b42d-cef7ac5b1c07".device = "/dev/disk/by-uuid/3f1d3add-27cd-4b76-b42d-cef7ac5b1c07";
  boot.initrd.luks.devices."luks-3cc39c35-81d3-4f4c-bc0d-176f66523fd7".device = "/dev/disk/by-uuid/3cc39c35-81d3-4f4c-bc0d-176f66523fd7";

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/FB8A-0F5E";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices =
    [ { device = "/dev/mapper/luks-3f1d3add-27cd-4b76-b42d-cef7ac5b1c07"; }
    ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
